### ISSUE TITLE
Images layouts

### ISSUE THREAD

**Issue by cedricdelpoux** [LeKoArts/gatsby-remark-design-system#5]
Hi, 

I'm looking for a way to make some custom images layout, like two images side by side, a grid of 3x2 and others. In *Catalog*, I saw some responsive views. Do you plan to implement this in your plugin? Otherwise, what do you recommend for me?

Thank you

**Comment by LekoArts** [comment]
I don't quite understand. Do you have any examples?

**Comment by cedricdelpoux** [comment]
Of course, for example I want to achieve these kind of result:
<img width="368" alt="screen shot 2018-07-31 at 11 20 07" src="https://user-images.githubusercontent.com/2683300/43450790-cfbc8048-94b3-11e8-814c-f6768fcb5931.png">
<img width="351" alt="screen shot 2018-07-31 at 11 19 02" src="https://user-images.githubusercontent.com/2683300/43450791-cfd3cafa-94b3-11e8-91ee-3476e0d5cf67.png">

maybe with a syntax like:
````
```images
layout: cutomlayout
images : 
 - ![alt](url)
 - ![alt](url)
 - ![alt](url)
 - ![alt](url)
```
````

**Comment by LekoArts** [comment]
In my opinion that's not the scope of this plugin. I don't see this as an integral part of a design system.

As you can write actual HTML in the markdown files you could use wrapper elements around your images and then use CSS to style it.

**Comment by cedricdelpoux** [comment]
Ok I understand. 
My goal is the same as yours: do not write html in markdown files. I want to keep my markdown clean. 

I saw you are active in gatsby community. Maybe you know some plugin wich can help me doing this.
Otherwise, I will try to use your work to make my plugin.

**Comment by LekoArts** [comment]
I don't think there's a plugin available right now which does exactly that. I personally would use HTML or a React component (which can be used with another plugin or maybe in the near future with MDX)
