### ISSUE TITLE
CMYK values of 100 cause potential text wrapping

### ISSUE THREAD

**Issue by padraigfl** [LeKoArts/gatsby-remark-design-system#6]
Hey Lennart, really neat Gatsby plugin here, thanks for making it!
Pretty small one here, I noticed if there is any of the CMYK values are 100 it can lead to the text potentially wrapping due to the fixed width of the containing div. 

Not super familiar with CMYK so I just made up the numbers here, but this seems to be a possible example:
<img width="337" alt="screen shot 2018-11-08 at 10 50 17" src="https://user-images.githubusercontent.com/14135877/48194224-52215e80-e344-11e8-9e63-daf7eba39f82.png">

**Comment by LekoArts** [comment]
Ah, thanks for the notice. I'll have it solved next week.

**Comment by LekoArts** [comment]
Closing this issue as I'll focus on https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-specimens now.
